---
title: "Notas do PAS 2018-2020 1ª Etapa"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows   # orientação por linhas
    social: menu   # insere menu de compartilhamento
    source_code: embed   # disponibiliza o código
runtime: shiny
---

```{r global, include=FALSE}
options(OutDec = ",")   # ponto de milhar
library(flexdashboard)
library(ggplot2)
notasPAS <- rio::import("NotasPAS2018.xlsx")   # utilizo o pacote rio para as tarefas de importar
                                                # e exportar devido à facilidade de uso
```

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput("Inscrição",   # nome do botão de escolha
            label = h3("Selecione o número de sua inscrição"),    # texto que aparecerá acima do botão
            choices = unique(notasPAS$Inscrição),    #   escolhas possíveis (números de inscrição)
            selected = 1)   # permite a seleção de um candidato por vez

```

As notas da 1ª etapa do subprograma 2018 do PAS (triênio 2018/2020) foram divulgadas pelo CEBRASPE no endereço: https://bit.ly/2J92dZZ.

\newline

O arquivo PDF foi convertido para excel, e a classificação relativa de cada participante pode ser consultada nos gráficos ao lado - a linha vermelha representa a nota do candidato escolhido. 

\newline

Por motivos de privacidade, decidiu-se mostrar apenas o número da inscrição dos participantes.

\newline

Para melhor visualização, maximize a página.

Row
-----------------------------------------------------------------------

### Escore Bruto 1

```{r}
texto_notaEB1 <- renderText(paste("Sua nota foi semelhante ou melhor do que a nota de",
                                  scales::percent(round(ecdf(notasPAS$EscoreBruto1)(notasPAS$EscoreBruto1)[notasPAS$Inscrição == input$Inscrição],2)),
                                  "dos participantes"))
renderPlot({
  
  ggplot(data = notasPAS, aes(EscoreBruto1)) +
    geom_histogram(bins = 10,
                  color = "royalblue",
                  fill = "lightblue",
                  boundary = 0) +
    geom_vline(xintercept = notasPAS$EscoreBruto1[notasPAS$Inscrição == input$Inscrição],
              color = "red",
              size = 2) +
    labs(x = "Escore Bruto 1",
        y = "Número de estudantes",
        title = texto_notaEB1()) +
    scale_x_continuous(breaks = seq(0, 10, by = 1)) +
    scale_y_continuous(labels = function(x) format(x, big.mark = ".")) +
    theme_classic() +
    theme(plot.title = element_text(size = 17))
  
})

```

### Escore Bruto 2

```{r}

texto_notaEB2 <- renderText(paste("Sua nota foi semelhante ou melhor do que a nota de",
                                  scales::percent(round(ecdf(notasPAS$EscoreBruto2)(notasPAS$EscoreBruto2)[notasPAS$Inscrição == input$Inscrição],2)),
                                  "dos participantes"))

renderPlot({
  
  ggplot(data = notasPAS, aes(EscoreBruto2)) +
    geom_histogram(bins = 10,
                  color = "royalblue",
                  fill = "lightblue",
                  boundary = 0) +
    geom_vline(xintercept = notasPAS$EscoreBruto2[notasPAS$Inscrição == input$Inscrição],
              color = "red",
              size = 2) +
    labs(x = "Escore Bruto 2",
        y = "Número de estudantes",
        title = texto_notaEB2()) +
    scale_x_continuous(breaks = seq(0, 100, by = 10)) +
    scale_y_continuous(labels = function(x) format(x, big.mark = ".")) +
    theme_classic() +
    theme(plot.title = element_text(size = 17))
  
})

```

Row
-----------------------------------------------------------------------

### Nota Redação

```{r}
texto_notaR <- renderText(paste("Sua nota foi semelhante ou melhor do que a nota de",
                                scales::percent(round(ecdf(notasPAS$NotaRedação)(notasPAS$NotaRedação)[notasPAS$Inscrição == input$Inscrição],2)),
                                "dos participantes"))
renderPlot({
  
  ggplot(data = notasPAS, aes(NotaRedação)) +
    geom_histogram(bins = 10,
                  color = "royalblue",
                  fill = "lightblue",
                  boundary = 0) +
    geom_vline(xintercept = notasPAS$NotaRedação[notasPAS$Inscrição == input$Inscrição],
              color = "red",
              size = 2) +
    labs(x = "Nota Redação",
        y = "Número de estudantes",
        title = texto_notaR()) +
    scale_x_continuous(breaks = seq(0, 10, by = 1)) +
    scale_y_continuous(labels = function(x) format(x, big.mark = ".")) +
    theme_classic() +
    theme(plot.title = element_text(size = 17))
  
})

```

### Nota Total

```{r}
texto_notaT <- renderText(paste("Sua nota foi semelhante ou melhor do que a nota de",
                                scales::percent(round(ecdf(notasPAS$NotaTotal)(notasPAS$NotaTotal)[notasPAS$Inscrição == input$Inscrição],2)),
                                "dos participantes"))
renderPlot({
  
  ggplot(data = notasPAS, aes(NotaTotal)) +
    geom_histogram(bins = 10,
                  color = "royalblue",
                  fill = "lightblue",
                  boundary = 0) +
    geom_vline(xintercept = notasPAS$NotaTotal[notasPAS$Inscrição == input$Inscrição],
              color = "red",
              size = 2) +
    labs(x = "Nota Total",
        y = "Número de estudantes",
        title = texto_notaT()) +
    scale_x_continuous(breaks = seq(0, 100, by = 10)) +
    scale_y_continuous(labels = function(x) format(x, big.mark = ".")) +
    theme_classic() +
    theme(plot.title = element_text(size = 17))
  
})

```
